// Generates the item-family back-fill migration from a dump of rate_reference descriptions.
//
//   npx supabase db query --linked "select item_description_raw raw from rate_reference" > dump.json
//   node scripts/item-families/generate.mjs dump.json supabase/migrations/<version>_item_families.sql
//
// Writes item_family (with category), item_catalog (family + size) and one item_alias per
// distinct description, all unconfirmed, then sets rate_reference.item_family_id /
// item_catalog_id / is_comparable by exact alias match. Re-runnable: every insert is
// `on conflict do nothing`, so an existing family/item/alias keeps whatever a human set.
import { readFileSync, writeFileSync } from 'node:fs'
import { CATS, classify, readSize } from './rules.mjs'

const [input, output] = process.argv.slice(2)
if (!input || !output) {
  console.error('usage: node generate.mjs <dump.json> <out.sql>')
  process.exit(1)
}
const text = readFileSync(input, 'utf8')
// `supabase db query` prints a JSON object ({ rows: [...] }) after a status line; a plain
// array of { raw } works too.
const starts = [text.indexOf('{'), text.indexOf('[')].filter((i) => i >= 0)
const parsed = JSON.parse(text.slice(Math.min(...starts)))
const rows = Array.isArray(parsed) ? parsed : parsed.rows

const q = (s) => (s == null ? 'null' : `'${String(s).replace(/'/g, "''")}'`)
const families = new Map()
const items = new Map()
const aliases = new Map() // exact raw -> item_key
let assigned = 0

for (const raw of new Set(rows.map((r) => r.raw ?? r.item_description_raw))) {
  const f = classify(raw)
  if (!f) continue
  const [cat, key, label, unit, comparable, , sized] = f
  if (!families.has(key)) families.set(key, { key, label, unit, comparable, category: CATS[cat] })
  const size = sized ? readSize(raw, key) : null
  const read = size && !('ambiguous' in size.spec)
  const itemKey = read ? `${key}-${size.label}` : key
  if (!items.has(itemKey)) {
    items.set(itemKey, { itemKey, family: key, label: read ? `${label} · ${size.label}` : label, spec: read ? size.spec : {}, unit, comparable })
  }
  aliases.set(raw, itemKey)
  assigned++
}

const fam = [...families.values()].sort((a, b) => a.key.localeCompare(b.key))
const cat = [...items.values()].sort((a, b) => a.itemKey.localeCompare(b.itemKey))
const ali = [...aliases.entries()].sort((a, b) => a[1].localeCompare(b[1]) || a[0].localeCompare(b[0]))

const sql = `-- Item families back-fill (docs/report-data-gaps-plan.md Phase 2).
--
-- Generated by scripts/item-families/generate.mjs from the ${rows.length} rate_reference rows
-- present on ${new Date().toISOString().slice(0, 10)}; agreed with the user before writing.
-- ${fam.length} families in ${new Set(fam.map((f) => f.category)).size} categories, ${cat.length} catalog items, ${ali.length} aliases.
--
-- Three levels:
--   category      new item_family.category -- the ~12 groups spend charts roll up to
--   item_family   the item TYPE rate benchmarks compare across vendors ('cpvc-elbow')
--   item_catalog  family + size read from the bill text, spec jsonb ({"dia_in": 1.5});
--                 lines whose size couldn't be read sit on the family's bare item
--
-- Every row is created UNCONFIRMED (is_confirmed = false) for a human to confirm, and each
-- distinct description gets an exact item_alias. Nothing fuzzy runs in the database: the
-- regex rules live in scripts/item-families/rules.mjs and only produced this mapping.
--
-- Going forward, a BEFORE INSERT trigger on rate_reference attaches family/catalog by exact
-- normalised-description match against item_alias. verify_document_extraction deletes and
-- re-inserts a bill's rows on every save, so the trigger covers new and re-saved bills
-- without touching that function. A description with no alias stays unassigned.

-- ----------------------------------------------------------------------------
-- category on item_family
-- ----------------------------------------------------------------------------
alter table public.item_family add column if not exists category text;
comment on column public.item_family.category is
  'Coarse spend group (e.g. Plumbing, Venue structures). Families are item types; categories roll them up for spend charts.';

-- ----------------------------------------------------------------------------
-- normalisation shared by item_alias and the lookup trigger
-- ----------------------------------------------------------------------------
-- Case and whitespace only. Sizes stay in: "astral elbow 1"" and "astral elbow 2"" are
-- different catalog items.
create or replace function private.normalize_item_description(p text)
returns text
language sql
immutable
set search_path = ''
as $$
  select lower(btrim(regexp_replace(coalesce(p, ''), '\\s+', ' ', 'g')))
$$;

-- ----------------------------------------------------------------------------
-- families
-- ----------------------------------------------------------------------------
insert into public.item_family (family_key, label, default_unit, is_comparable, category, is_confirmed)
values
${fam.map((f) => `  (${q(f.key)}, ${q(f.label)}, ${q(f.unit)}, ${f.comparable}, ${q(f.category)}, false)`).join(',\n')}
on conflict (family_key) do nothing;

-- ----------------------------------------------------------------------------
-- catalog items (family + size)
-- ----------------------------------------------------------------------------
insert into public.item_catalog (item_family_id, item_key, canonical_label, spec, unit_normalized, is_comparable, is_confirmed)
select fam.id, v.item_key, v.label, v.spec::jsonb, v.unit, v.comparable, false
from (values
${cat.map((c) => `  (${q(c.family)}, ${q(c.itemKey)}, ${q(c.label)}, ${q(JSON.stringify(c.spec))}, ${q(c.unit)}, ${c.comparable})`).join(',\n')}
) as v(family_key, item_key, label, spec, unit, comparable)
join public.item_family fam on fam.family_key = v.family_key
on conflict (item_key) do nothing;

-- ----------------------------------------------------------------------------
-- aliases: one per distinct normalised description
-- ----------------------------------------------------------------------------
insert into public.item_alias (item_catalog_id, raw_description, normalized_description, source)
select distinct on (private.normalize_item_description(v.raw))
  ic.id, v.raw, private.normalize_item_description(v.raw), 'import'
from (values
${ali.map(([raw, key]) => `  (${q(raw)}, ${q(key)})`).join(',\n')}
) as v(raw, item_key)
join public.item_catalog ic on ic.item_key = v.item_key
where private.normalize_item_description(v.raw) <> ''
order by private.normalize_item_description(v.raw), v.raw
on conflict (normalized_description) do nothing;

-- ----------------------------------------------------------------------------
-- back-fill rate_reference by exact alias match
-- ----------------------------------------------------------------------------
update public.rate_reference rr set
  item_family_id = ic.item_family_id,
  item_catalog_id = ic.id,
  is_comparable = ic.is_comparable
from public.item_alias ia
join public.item_catalog ic on ic.id = ia.item_catalog_id
where ia.normalized_description = private.normalize_item_description(rr.item_description_raw)
  and rr.item_catalog_id is null;

-- ----------------------------------------------------------------------------
-- going forward: attach family/catalog on insert by exact alias match
-- ----------------------------------------------------------------------------
create or replace function private.rate_reference_assign_item()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.item_catalog_id is null then
    select ic.item_family_id, ic.id, ic.is_comparable
      into new.item_family_id, new.item_catalog_id, new.is_comparable
    from public.item_alias ia
    join public.item_catalog ic on ic.id = ia.item_catalog_id
    where ia.normalized_description = private.normalize_item_description(new.item_description_raw);
    -- select into leaves the targets null on no match; keep the column default instead
    if new.is_comparable is null then
      new.is_comparable := true;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists rate_reference_assign_item on public.rate_reference;
create trigger rate_reference_assign_item
  before insert on public.rate_reference
  for each row execute function private.rate_reference_assign_item();
`

writeFileSync(output, sql)
console.log(`families ${fam.length}, items ${cat.length}, aliases ${ali.length}, descriptions assigned ${assigned}`)
