-- Performance remediation plan (docs/performance-remediation-plan.md) 7.11.
--
-- document_extraction_document_idx (source_document_id) was added by
-- 20260817000002 to replace the plain index the old single-column unique
-- constraint provided implicitly. But that same migration also added
-- document_extraction_source_document_id_bill_index_key, a unique constraint
-- on (source_document_id, bill_index) -- and a btree backing a composite
-- unique constraint already supports both an equality filter and an ordered
-- fetch on its leading column alone. document_extraction_document_idx is a
-- pure duplicate: same leading column, strictly narrower, maintained on
-- every insert/update/delete for no read benefit over the constraint's own
-- index.
--
-- NOTE: unlike CREATE INDEX CONCURRENTLY (which scans/builds over the whole
-- table and so needs CONCURRENTLY to avoid blocking writes for a long time),
-- a plain DROP INDEX only removes a catalog entry -- it takes a brief
-- ACCESS EXCLUSIVE lock regardless of table size, comparable to any other DDL
-- statement in a migration. `supabase db push` runs each migration inside a
-- transaction, and CONCURRENTLY cannot run inside one (SQLSTATE 25001) -- so
-- this deliberately omits it, rather than needing a special non-transactional
-- apply path. Not verified against a live plan -- review before applying.

DROP INDEX IF EXISTS public.document_extraction_document_idx;
