-- Board pack -- reporting-blueprint.md §5 ("The board pack -- the same Brief
-- rendered to a single PDF and a matching workbook, on a schedule").
--
-- The board pack is the Executive Brief frozen to two downloadable files:
--   * a complete .xlsx workbook (the primary, outward-format deliverable --
--     the org's outward format is Excel, a permanent decision), and
--   * a basic text .pdf rendering of the same figures (pdf-lib; there is no
--     headless-chromium HTML-to-PDF path in this stack).
-- Both are generated by a self-scheduling `board_pack` job, drained by the
-- exact same queue infrastructure as `flags_run` (lib/jobs/drain.ts,
-- worker/index.ts, app/api/jobs/tick/route.ts). The handler
-- (lib/jobs/handlers/board-pack.ts) re-inserts its own next run one week out,
-- so nothing outside this seed row ever has to enqueue a board_pack job again.
--
-- One `board_pack` row == one generated pack: the pair of storage objects it
-- produced, plus a jsonb snapshot of the 5 headline KPIs as they stood at
-- generation time (so a historic pack's tiles can be shown without recomputing
-- against today's data).
--
-- RLS: any active staff member may read board_pack rows and download the files
--   (`private.is_staff()`), matching status_export_batch. All writes happen via
--   the service-role key inside the job handler (§4.5) -- there is deliberately
--   no insert/update/delete policy for `authenticated`, same posture as
--   job_queue and source_document_assignee.

-- ============================================================================
-- 1. job_type -- add 'board_pack' to the CHECK constraint
-- ============================================================================
-- Same drop/re-add shape as 20260814000006_flags_run_job_type.sql. The list
-- below is the full current set (four original types + flags_run) plus the new
-- one -- re-derived from 20260814000006, which is the latest migration to touch
-- this constraint.
alter table public.job_queue drop constraint job_queue_job_type_check;
alter table public.job_queue add constraint job_queue_job_type_check
  check (job_type in
    ('extract_document','poll_batch','generate_export','rasterize_retry','flags_run','board_pack'));

-- ============================================================================
-- 2. public.board_pack
-- ============================================================================
create table public.board_pack (
  id            bigint generated always as identity primary key,
  -- The event this pack summarises. `on delete set null` (not cascade): a pack
  -- is a historic artifact worth keeping even if its event row is later removed.
  event_id      bigint references public.event(id) on delete set null,
  generated_at  timestamptz not null default now(),
  -- Storage object paths inside the private `board-packs` bucket. Never a raw
  -- URL -- the app hands out short-lived signed URLs (§4.3).
  xlsx_path     text not null,
  -- Null when PDF rendering was skipped or failed -- the workbook is the
  -- deliverable of record; the PDF is best-effort.
  pdf_path      text,
  -- The 5 Brief KPI tiles (label / value / delta / tone) as of generation.
  kpi_snapshot  jsonb not null default '{}'::jsonb,
  -- auth.uid() of the admin who triggered a manual "generate now"; null for a
  -- scheduled run.
  generated_by  uuid references auth.users(id) on delete set null,
  created_at    timestamptz not null default now()
);

-- Recent-packs-for-an-event lookup (the /reports/brief footer list).
create index board_pack_event_generated_idx
  on public.board_pack (event_id, generated_at desc);
create index board_pack_generated_by_idx
  on public.board_pack (generated_by) where generated_by is not null;

alter table public.board_pack enable row level security;
alter table public.board_pack force row level security;

-- Read: any active staff member (same as status_export_batch). Event scoping is
-- an application-level visibility concern, not RLS (lib/events/current.ts).
create policy board_pack_select_staff on public.board_pack for select to authenticated
  using ((select private.is_staff()));

-- No insert/update/delete policy for `authenticated`: every write is the job
-- handler using the service-role key. A stray `.insert()` from app code fails
-- with permission denied, by design -- same posture as job_queue.
grant select on public.board_pack to authenticated;
revoke insert, update, delete on public.board_pack from authenticated;

-- ============================================================================
-- 3. Storage bucket -- private `board-packs`
-- ============================================================================
-- Mirrors 20260808000027_storage_policies.sql's `invoice-documents` setup:
-- created private, no public URLs ever, staff-read via signed URLs only.
insert into storage.buckets (id, name, public)
values ('board-packs', 'board-packs', false)
on conflict (id) do nothing;

-- Read: any active staff member. The app still only ever serves these through
-- short-lived signed URLs generated server-side (lib/reports/board-pack/...).
create policy "staff read board packs" on storage.objects for select to authenticated
  using (bucket_id = 'board-packs' and (select private.is_staff()));

-- Writes (insert/update/delete): service-role only -- the job handler. No
-- policy for `authenticated`, matching board_pack's own table posture and
-- job_queue's "all writes via service_role".

-- ============================================================================
-- 4. Seed the first run
-- ============================================================================
-- After this, lib/jobs/handlers/board-pack.ts's scheduleNextRun re-queues the
-- job one week out on every completion -- nothing else ever inserts a
-- board_pack job row again (same one-shot seed as flags_run in
-- 20260814000006).
insert into public.job_queue (job_type, payload, run_after)
values ('board_pack', '{}'::jsonb, now());
